name: Build Raspberry Pi Image

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04-arm
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: check platform
      run: |
        uname -m

    - name: install build dependencies
      run: |
        sudo apt update
        sudo apt install -y qemu-user-static
        sudo apt install -y openssl

    - name: build image
      id: build
      run: |
        cd build
        bash build-image.sh
        echo "version=1.1-${GITHUB_SHA::6}" >> "$GITHUB_OUTPUT"

    - name: create checksum
      run: |
        cd build/pi-gen/deploy
        export image_filename=$(ls *-img.xz)
        sha256sum ${image_filename} > ${image_filename}.sha256sum
